[[redirects]]
  from = "https://arnold-c.netlify.app"
  to = "https://callumarnold.com"
  status = 301
  force = true
  
[[redirects]]
  from = "http://arnold-c.rbind.io"
  to = "https://callumarnold.com"
  status = 301
  force = true
  
[[redirects]]
  from = "https://arnold-c.rbind.io"
  to = "https://callumarnold.com"
  status = 301
  force = true
  
[[redirects]]
  from = "http://www.arnold-c.rbind.io"
  to = "https://callumarnold.com"
  status = 301
  force = true
  
[[redirects]]
  from = "https://www.arnold-c.rbind.io"
  to = "https://callumarnold.com"
  status = 301
  force = true
       
     
   
