---
page-layout: full
format:
    html:
        toc: false
---

## Research


```{r}
#| echo: false
icon_link <- function(type, icons, url, label) {
    paste0(
        '<',
        type,
        ' class="',
        icons,
        '" onclick="window.location.href=\'',
        url,
        '\'">',
        label,
        '</',
        type,
        '>'
    )
}

paper_button <- function(url, label = "Paper") {
    c(
        '<div class="btn btn-paper">',
        icon_link(type = "p", icons = "bi bi-journal", url, label),
        '</div>'
    )
}

gh_button <- function(url) {
    icon_link(type = "div", icons = "btn btn-github bi bi-github", url, "Code")
}

website_button <- function(url) {
    icon_link(type = "div", icons = "btn btn-website bi bi-browser-chrome", url, "Website")
}

project_card <- function(
    title,
    github,
    papers,
    website,
    text
    ) {

    if (hasArg(papers)) {
        if (length(papers) > 1) {

            paper_icons <- purrr::map2(
                seq_along(papers),
                papers,
                ~paper_button(.y, paste0("Paper ", .x))
            )

        } else {
            paper_icons <- paper_button(papers, "Paper")
        }

    }

    card_details <- c(
        '::: {.g-col-12 .g-col-md-6}',
        '<div class="card card-project h-100">',
        paste0('<h2 style="font-size: 1.45rem">', title, '</h2>'),
        '<div class="container">',
        if (hasArg(website)) { website_button(website) },
        if (hasArg(github)) { gh_button(github) },
        if (exists("paper_icons")){ unlist(paper_icons) },
        '</div>',
        text,
        '</div>',
        ':::'
    )

    cat(card_details, sep = "\n")
}
```

:::: {.grid}

```{r}
#| echo: false
#| results: asis
project_card(
    "Data4Action (COVID-19 at Penn State)",
    papers = "https://www.nature.com/articles/s41598-022-12499-5",
    text = "
A longitudinal cohort study, comprising of two geographically related cohorts,  that aims to examine the effect of Penn State University students on the SARS-CoV-2 incidence in the surrounding community.
We have recently published a the interim serological results in Nature Scientific Reports, which can be found [here](https://doi.org/10.1038/s41598-022-12499-5).
The second part of the project focuses on relating the differential exposures observed in the
student cohort to latent risk profiles, examining the potential impact of interventions to reduce infections.
"
)
```

```{r}
#| echo: false
#| results: asis
project_card(
    "Measles in the DRC",
    github = "https://www.github.com/arnold-c/drc-urgepi",
    text = "
An ongoing collaboration with Médecin Sans Frontières' (MSF) Epicentre unit to analyze measles seroprevalence in the ex-Katanga region of the Democratic  Republic of Congo (DRC).
The intial project examined the role of new laboratory testing facilities on the speed of diagnosis and outbreak response decisions.
The second project examines the impact of Supplemental Immunization Activities in the ex-Katanga region; principally, characterizing the spatial and age-specific seronegativity, and examining the relationship between optical density (OD) distributions and seropositivity thresholds using finite mixture models and generalized additive models.
"
)
```


```{r}
#| echo: false
#| results: asis
project_card(
    "Outbreak Detection and Surveillance",
    github = "https://github.com/arnold-c/OutbreakDetection",
    text = "
A simulation study of the potential use and effectiveness of a rapid diagnostic test (RDT) in the surveillance of, and outbreak detection for, measles in near-elimination status regions.
    This project was conducted for Gavi and the WHO to assist in guiding the target product profile for a potential measles RDT for public health surveillance purposes.
    "
)
```

::::

</br>

<details>
<summary>Click to view prior projects</summary>

:::: {.grid}

```{r}
#| echo: false
#| results: asis
project_card(
    "Waning Measles Immunity Among Infants in Canada",
    papers = c("https://doi.org/10.1542/peds.2019-0630", "https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0287765", "https://www.sciencedirect.com/science/article/pii/S0264410X23011921"),
    text = "A prospective cross-sectional serology study of Canadian newborns and mothers
assessing the rate of waning measles, varicella, and mumps antibodies in infants,
including subgroup analysis by vaccination status. A retrospective analysis of
waning measles antibody titers (PRNT) in stored sera from a separate cohort of
Canadian newborns was published as part of the study, and can be found
[here](https://doi.org/10.1542/peds.2019-0630)"
)
```

::::

</details>


## Teaching
:::: {.grid}

```{r}
#| echo: false
#| results: asis
project_card(
    "An Introduction to Git and GitHub",
    website = "https://psu-git.callumarnold.com",
    github = "https://www.github.com/arnold-c/psu-intro-to-git",
    text = "
Designed and create a 2-hour workshop on the basics of Git and GitHub to graduate students, postdocs, and faculty at the Center for Infectious Disease Dynamics at Penn State University.
Focusses on building a conceptual understanding of Git and GitHub, and how it can be used to improve research workflows by providing clear examples that are directly relevant to infectious disease researchers.
"
)
```

```{r}
#| echo: false
#| results: asis
project_card(
    "SISMID Modeling Infectious Diseases",
    website = "https://sismid2023.callumarnold.com",
    github = "https://www.github.com/arnold-c/sismid-module-02_2023",
    text = "
Created the website and rewrote the teaching materials for the 2023 SISMID module 2 (Mathematical Models of Infectious Diseases), that introduced students to the basics of mathematical modeling of infectious diseases.
Additionally, I wrote and delivered the lecture on understanding heterogeneity in models.
"
)
```

```{r}
#| echo: false
#| results: asis
project_card(
    "Julia for Epidemiologists",
    website = "https://juliaepibook.callumarnold.com/",
    github = "https://github.com/arnold-c/JuliaEpiHandbook",
    text = "
I am currently in the process of (slowly) writing a book on using Julia for epidemiological research.
The book is aimed at epidemiologists with no prior programming experience, and will cover the basics of Julia, and how to use it for epidemiological research.
The [EpiRHandbook](https://epirhandbook.com/en/) is an excellent resource for new and experienced epidemiologists, but Julia has many advantages over R (and certainly some disadvantages), and I hope this book will serve a similar purpose and help epidemiologists thinking about the transition to Julia.
"
)
```

::::
