---
title: "Reflections from 3 years of Neovim"
subtitle: "Neovim for Science: Post 01"
date: "2026-09-26"
description: |
    The first in an unorganized series of thoughts about using Neovim for scientific computing.
categories:
    - neovim
    - r
    - julia
    - quarto
    - science
    - repl
    - ide
image-alt: "Photo by <a href='https://unsplash.com/@timberfoster?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText'>Tim Foster</a> on <a href='https://unsplash.com/photos/qefCF3r4Eoc?utm_source=unsplash&utm_medium=referral&utm_content=creditCopyText'>Unsplash</a>"
---

A few years ago I made the decision to go all-in with [Neovim](https://neovim.io).
If you're not family with Vi(m) or Neovim, it's a fairly bare-bones, but incredibly powerful, text editor.
If you've ever opened a file in a Unix terminal, whether that be on your Mac or a Linux machine, or even a server, there's a good chance you've used Vi(m).

While switching to Neovim is certainly not unheard of, particularly in the wider programming world, I can't say I know many scientists (outside of CS, that is) who use it.
In a world where everyone is using RStudio and Positron for R (and increasingly Python) programming, and VSCode dominates everything else, why would I possibly move to a text editor that doesn't have all of the creature comforts that are baked into modern IDEs?

Over the next couple of posts I hope to answer that question, and maybe even convince you to give it a try.
The first post in this mini-series will outline my motivations for switching and the bigger picture, and the subsequent posts will focus on the technical aspects and how I've made it work for me and my needs in scientific computing.
Long story short, I've found it to be a really enjoyable experience, and it has helped me become a better programmer through gaining a deeper understanding of the tools I use every day, which has transferred back to a better understanding of the languages I use for my work.

## Where I'm coming from

Before we talk about motivations, I think it's important to outline the type of work that I do, and what tools I've used in the past, as no editor is a one-size-fits-all solution.

In my day-to-day work, I use the R and Julia programming languages to clean lots of population-level infection data, build statistical (think GLM) and dynamical (think SIR) models, create lots of figures, and write papers and summary reports using [Quarto](https://quarto.org) notebooks and [Typst](https://typst.app/) (as a $LaTeX$ replacement).
All of this is fairly typical of a scientist in the modern era, where most of our work is now performed on computers.

As a result of being a researcher whose work is entirely computational, it's important that the text editor I use fits my needs.
But these needs are not the same as a software developer's, who is the primary target for most IDEs, so seemingly inconsequential grievances can be deal-breakers for researchers.


## What I need & want from an editor

Given the work outlined above, there are a number of non-negotiable features that I **need** from an editor:

<div class="box" style="padding-bottom:0">
1. **Interactive editing** of R and Julia code, including the ability to send **code chunks** to a REPL/console.<a id="lst-repl-send"></a>
2. **Syntax highlighting** for R, Julia, and Markdown (and ideally $LaTeX$ and/or Typst).<a id="lst-syntax-highlighting"></a>
3. **Autocompletion** of R and Julia code, including in a Quarto notebook.<a id="lst-autocomplete"></a>
4. **Easy plot creation and viewing**.
</div>

Most of these should hopefully be self-explanatory given the workflow I outlined above, and it was not immediately obvious that all were possible within Neovim (within a reasonable enough time-frame before I gave up and went back to what I was used to).

There are also a number of features that I **want** from an editor, but could live without:

<div class="box" style="padding-bottom:0">
1. **First-class VCS (Git/Jujustu) integration**.
2. **Spell checking**.
3. **Code formatting**.
4. **Extensibility** through plugins as I decide to learn new languages or workflows.
5. **Quick start up times**.
6. **Simple configuration** of keymaps, snippets, etc.
7. **Easy navigation** of files and projects.
8. **Good file manipulation** (e.g., moving, copying, deleting, etc.).
</div>

## What's wrong with RStudio & VSCode?

Like most people, I started learning R using RStudio, and I still think it's a great tool.
It is incredibly easy to set up, and it does all of my four essentials for R out of the box.
It can also do most of my wants with somewhat minimal effort.
So why switch?

As mentioned, I've been using Julia more and more as I've transitioned from traditional epidemiological analysis with statistical models to building dynamical models of infectious disease, which are much more computationally intensive (particularly for ensemble stochastic simulations) and benefit from a faster language.
Plus, it's fun learning a new language and has made me a better programmer in general, which benefits my R work as well.
As a result, I haven't used R much for serious work in the last couple of years, and last I checked, RStudio didn't support Julia (outside of using a binding like the [JuliaCall](https://github.com/Non-Contradiction/JuliaCall) R package from within R scripts, which is not ideal from a reproducibility standpoint and doesn't address needs [2.](#lst-syntax-highlighting) and [3.](#lst-autocomplete) particularly well).
It's certainly not essential to use the same IDE for all languages, but it definitely makes it easier to switch between projects, and there are fewer configurations to maintain and get used to.

That rules out RStudio, but what about Positron & VSCode?
Well, I actually had switched to using VSCode entirely for my R code about 5 years ago.
The main reason was not because I was starting to learn Julia (though it did coincide with this), but actually because ~~*RStudio couldn't handle*~~ I didn't search hard enough to figure out how to get RStudio to handle some of my larger projects.^[The issue below just outlines my reasoning at the time, and it can be worked around by sending code to a tmux terminal session within RStudio's terminal pane (see [this post](https://support.posit.co/hc/en-us/articles/115010737148-Using-the-RStudio-Terminal-in-the-RStudio-IDE#send) for more detail).]

Because I was working with larger and larger datasets, and often trying to make use of parallelization to speed up long-running code, I was running into memory issues with RStudio (at the time I was working on a 10 year old MacBook Pro that had seen it's fair share of hardships and was absolutely not up to the task).
Unfortunately, RStudio's biggest strength was also it's biggest weakness for me: by including everything within the IDE, by default your R code is sent to the integrated console that is bound to your editor.
If RStudio crashes, it takes your R session down with it.
And in my case, it was crashing a lot, requiring me to restart long computations far more often than was actually required: the same scripts (technically [`{targets}`](https://books.ropensci.org/targets/) pipelines) would run fine in the terminal!^[If you use R and you haven't come across `{targets}` yet, do yourself a favor and go learn it now! Not only does it make your code more reproducible by removing the questions about which scripts need to be run when something is updated (this comes with the added benefit of not needing to re-run calculations when their dependencies haven't changed) but it also makes it easier to debug as it encourages smaller modular functions.]
It turns out there are ways to circumvent this issue using the technique described below, and it's [been around for a while](https://www.r-bloggers.com/2018/09/4-ways-to-be-more-productive-using-rstudios-terminal/), so this point was actually my biggest weakness, not RStudio's, but the end result was the same as I mostly use Julia now, requiring a new editor anyway.

VSCode solved this issue for me because it has an integrated terminal (like RStudio, it turns out), but by default all code is sent to the terminal that is currently open.
At first glance, this doesn't seem to be any different from RStudio's integrated console.
However, the difference is that I could use a terminal multiplexer like [tmux](https://github.com/tmux/tmux/wiki/Getting-Started) from within the VSCode terminal, allowing me to separate my R session from my editor.
If you're not familiar with terminal multiplexers like tmux, that's OK; I wasn't either at first.
Essentially, they allow you to create multiple persistent terminals that will stay open and running even if you close your terminal window.
They are especially useful when working on servers and you want to guard against accidentally losing connection because of internet issues etc., but as you can imagine, they come in handy for local development too.
In my case, I could open up a tmux session (in the VSCode terminal), start R, and then VSCode would send the commands to the R session running in tmux.
If VSCode crashed, I could just re-open it and reconnect to the tmux session, which would still be running.
And better yet, because VSCode is the most [popular editor](https://survey.stackoverflow.co/2022/#most-popular-technologies-new-collab-tools), there's likely an extension available that will solve a problem you are facing.
This includes an extension for working with R: [vscode-r](https://github.com/REditorSupport/vscode-R).
It's not perfect, and there are certainly some niceties from RStudio that are missing or need some work to be configured (e.g., setting up [RStudio addins](https://github.com/REditorSupport/vscode-R/issues/405) to add Roxygen docstrings), but it was a pretty good solution that I was happy with for a couple of years.^[These issues have since been solved by the development of the Positron IDE, designed as a wrapper around VSCode by the team behind RStudio to replace RStudio. However, there are still a few reasons why I haven't switched back to Positron.]
And VSCode is the editor primarily suggested for Julia, so it was a natural fit to have everything in one place.

So again, why switch?

Over time, there were small details I noticed were annoying me about the VSCode (and RStudio) approach.
Firstly, it was slow to start up and get going with a project.
This is certainly not the biggest issue, but it adds just a little bit of friction each time you have an idea you want to test out.
If I'm working on one project and I realize I should reimplement a function in another, I want to be able to move instantly to that project and start working on it, not wait for VSCode to fire up.
The extra time resulted in me having multiple VSCode windows open at once, which is not ideal for many reasons (particularly on old hardware).
Secondly, and this was a surprisingly large motivating factor, the plotting window in VSCode is baked in to the editor.
In a similar vein to the issue with RStudio defaulting to sending code to a console, relying on an integrated plotting window made working off a small laptop annoying.
Most of the time I have a monitor, but there have been enough occasions where I only have the small screen of my laptop to work with, and each time I want the code to take up the vast majority of the space.
Normally I don't need to see plots as I'm writing code, and it's possible to hide and show the plot windows, but I found that I need to view them frequently enough to notice how slow this is to accomplish using a mouse (I couldn't find any settings that would allow me to do this using keyboard shortcuts, though this could again be a me-issue).
What I wanted was to be able to send the plot window to a different "space/desktop" on my laptop, and then I could switch between the editor and the plot window with a keyboard shortcut I set up in System Preferences.^[Something similar could be achieved using a tiling window manager like [yabai](https://github.com/koekeishiya/yabai/) or [aerospace](https://github.com/nikitabobko/AeroSpace) for MacOS, which I use extensively (but that's for a later day) or [I3](https://i3wm.org)/[Sway](https://swaywm.org) for Linux. I'm not sure if something similarly competent exists for Windows, but [this package](https://github.com/LGUG2Z/komorebi) seems like a promising start.].



:::{title="What about Zed?".callout-note}

Now before you ask "_What about [Zed](https://zed.dev/)?_", yes, I have tried it, but it's not quite ready for what I need.
Mainly, there is no good way to send code to a REPL (see [1.](#lst-repl-send)).
There is currently a [proposal](https://github.com/zed-industries/zed/pull/53221) to fix this, but until this is merged I won't be using Zed for my work-related projects.

:::


## What does Neovim do better?

Ok.
So after all that, what's the motivation behind Neovim?
Well, because Neovim is a small text editor built around Lua that lives in the terminal, it is incredibly easy to hack on, and it can easily leverage the vast array of command line interface (CLI) tools that exist to expand its functionality in more directions than you can possibly explore.
And it's _fast_.

In later posts in this series I will dive into exactly how I have my Neovim set up for scientific development, but in brief, because Neovim lives in the terminal, my setup now revolves around tmux.
This allows me to not only create and switch between multiple projects with ease, but (and perhaps more importantly) also provides some persistence to projects and their state.
This last point is more useful than I first had imagined.
There have been a number of occasions where I have been working on a project with long-running simulations, so wish to switch to another while I'm waiting.
When using VSCode, this requires booting up another window that is resource-intensive and manually navigating around.
If you do this with a numerous projects your desktop environment can quickly become visually cluttered and awkward to navigate, not to mention the strain on your CPU and RAM.
With a Neovim and tmux-based setup, it's as simple as as couple of keybindings to switch between the attached tmux sessions.
When you're ready to go back, you don't need to leave your application or close any windows -- you just switch.

Tmux also provides great flexibility in how you set up your environment.
If, for example, in one research project you need to see your text editor, have a terminal session rendering a quarto website (that you want to easily monitor for errors), have a view with an active REPL to test out code in, plot viewers, and git history, this is all achievable, malleable, and only requires a keybinding to navigate between the tmux windows and panes.
And then when you're done with a view e.g., the quarto rendering pane, you can just remove it.
With VSCode, it is possible to achieve this setup, but I find it to be far more awkward to adapt, including when I require drastically different views between projects.

With respect to Neovim itself as an editor, I find myself generally faster using it compared to using VSCode.
The keyboard shortcuts and its modal nature^[Modal editors are those that have different "modes" that you switch between to perform different functions. Neovim has 4: Normal, Insert, Visual, and Command. Normal mode is the baseline where you are not able to edit text, but you can navigate around the file using keyboard shortcuts like `f)` to find the next `)` relative to your cursor position and `h`, `j`, `k`, and `l` to move the cursor left, down, up, and right, respectively. Insert mode is entered by pressing the `i` key in Normal mode and allows you to edit text at your current position, with `I` and `A` being used to enter insert mode at the start or end of the current line, respectively. This is just scratching the surface of (Neo)vim's keyboard-centric workflow, but I will explore some of it later in the series.] takes time to become fluent in, but when you do, it truly feels like you are only limited by how fast you can move your fingers on the keyboard.
Going back to an editor that requires heavy mouse interaction genuinely feels like a step backwards^[You can install a VSCode extension to use the default Vim keybindings and modes, which gets you 80% of the way there, but that last 20% is very much felt. For example, there are Neovim plugins like [flash.nvim](https://github.com/folke/flash.nvim) that help speed up navigation through a file, or [snacks.nvim](https://github.com/folke/snacks.nvim) to speed up file searching with preview windows, that are focussed on speeding up codebase navigation via the keyboard, and they aren't easily replicated in VSCode].

## What are the pain points, and are they deal breakers?

Although Neovim and a terminal-based setup have been beneficial to my development experience (in both definitions of the term "experience"), there are some downsides.
The primary ones being that there is a very steep learning curve, and you have to maintain your development environment.

The Neovim editor with its modal nature was unlike any editor I had used before -- there was a significant adjustment period where I constantly had to remind myself how and why to switch between modes (mostly Normal, Insert, and Visual).
I kept wanting to revert back to a traditional editor where I could just type and click and highlight text with my mouse.
Resisting this instinct for the first couple of days paid off and I was soon able to move around files relatively quickly (albeit still at a diminished pace).
Now, the modal editing experience with its keyboard-first workflow feels like the correct one and I'm always looking for approaches to bring it to other environments.

The other pain point is the nature of Neovim being a text editor first and foremost, albeit one that can be and has been extended into something that more resembles an IDE.
Out of the box, Neovim doesn't render line numbers, let alone provide context-aware/language-specific syntax highlighting for my code files, nor does it include autocomplete.
However, as I mentioned earlier, because it is written with Lua as a first-class citizen it is incredibly easy to hack on, so there is a vast set of plugins you can quickly install to add any functionality you may find is missing.
You can even quickly write your own if you can't find one to your liking.
Additionally you configure all your keybindings in Lua, allowing you to easily trigger both simple and complex actions -- this is far more sane than trying to use JSON, as in VSCode.
This flexibility, however, is a blessing and a curse.
On the one hand it means you have only what you need and none of what you don't, making it incredibly fast as the things you care about.
On the other hand, though, you need to spend time figuring out what it is you need, how to install and set up the missing plugins, and also resolving any breaking changes that may be introduced by updates to plugins your Neovim configuration relies on (though I find this isn't actually that common any more).

For me, neither of these issues are deal breakers.
In fact, through the process of learning to manage these features of the system, I believe I have gained a greater understanding of how my computer works, allowing me to interact with it in a more efficient manner.
You may feel differently and decide the trade-offs are not worth it for your situation.

## Overview

The software development world has changed a lot over the 3 years since I made the switch.
With the rise of AI coding agents, we are finding ourselves writing less and less code manually; instead dealing more with architectural and design decisions, and reviewing code that is produced by the coding agents.
For this purpose, I have found that my Neovim and tmux setup has become even more productive relative to a traditional IDE.
This is particularly the case given that most coding agents are designed around their own terminal user interface (TUI) e.g., Claude Code and OpenAI's Codex.
Having my editor based in the terminal has allowed me to quickly adapt my workflow to the emerging era of AI-based development; for example, quickly launching an agent in a new tmux pane, extending my Neovim setup so I can send messages from Neovim with context to the agent (e.g., file names and line numbers), and leveraging more advanced Git features like worktrees (and Jujutsu workspaces) to develop ideas in parallel on a project through terminal commands that spin up coding agents in their own docker sandboxes with isolated versions of the project's codebase.
I will touch on some of these features next.
